In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
import torch
import torch.optim as optim
import torch.nn as nn
from torchviz import make_dot

# Gradient Descent

In [2]:
true_b = 1
true_w = 2
N = 100

np.random.seed(42)
x = np.random.rand(N, 1)
epsilon = (.1 * np.random.randn(N, 1))
y = true_b + true_w * x + epsilon

In [3]:
idx = np.arange(N)
np.random.shuffle(idx)

train_idx = idx[:int(N* .8)]
val_idx = idx[int(N* .8):]

x_train, y_train = x[train_idx], y[train_idx]
x_val, y_val = x[val_idx], y[val_idx]

In [4]:
np.random.seed(42)
b = np.random.randn(1)
w = np.random.randn(1)
print(b, w)

[0.49671415] [-0.1382643]


In [5]:
yhat = b + w * x_train

In [6]:
error = (yhat - y_train)
loss = (error ** 2).mean()
print(loss)

2.7421577700550976


In [7]:
b_grad = 2 * error.mean()
w_grad = 2 * (x_train * error).mean()
print(b_grad, w_grad)

-3.044811379650508 -1.8337537171510832


In [8]:
lr = 0.1
print(b, w)

b = b - lr * b_grad
w = w - lr * w_grad

print(b, w)

[0.49671415] [-0.1382643]
[0.80119529] [0.04511107]


# Linear Regression in Numpy

In [9]:
# step 0
np.random.seed(42)
b = np.random.randn(1)
w = np.random.randn(1)
print(b, w)

# sets lr
lr = 0.1
n_epochs = 1000
for epoch in range(n_epochs):
    # step 1
    yhat = b + w * x_train
    
    # step 2
    error = (yhat - y_train)
    loss = (error ** 2).mean()

    # step 3
    b_grad = 2 * error.mean()
    w_grad = 2 * (x_train * error).mean()

    # step 4
    b = b - lr * b_grad
    w = w - lr * w_grad

print(b, w)

[0.49671415] [-0.1382643]
[1.02354094] [1.96896411]


In [10]:
# use sklearn
linr = LinearRegression()
linr.fit(x_train, y_train)
print(linr.intercept_, linr.coef_[0])

[1.02354075] [1.96896447]


# PyTorch

In [9]:
scalar = torch.tensor(3.14159)
vector = torch.tensor([1, 2, 3])
matrix = torch.ones((2, 3), dtype=torch.float)
tensor = torch.randn((2, 3, 4), dtype=torch.float)

print(scalar)
print(vector)
print(matrix)
print(tensor)

tensor(3.1416)
tensor([1, 2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[[ 1.8736, -0.1530, -0.0186,  1.0426],
         [ 0.6630, -1.8434,  1.0565,  0.7662],
         [-0.5761, -0.4993, -0.7697,  1.0342]],

        [[-1.8418,  1.5584, -0.0254, -1.2915],
         [-1.6358,  0.6254, -1.1440, -2.8654],
         [ 2.7868,  0.3134, -1.2294, -0.7108]]])


In [10]:
print(tensor.size(), tensor.shape)

torch.Size([2, 3, 4]) torch.Size([2, 3, 4])


In [11]:
print(scalar.size(), scalar.shape)

torch.Size([]) torch.Size([])


In [12]:
same_matrix = matrix.view(1, 6)
same_matrix[0, 1] = 2
print(matrix)
print(same_matrix)

tensor([[1., 2., 1.],
        [1., 1., 1.]])
tensor([[1., 2., 1., 1., 1., 1.]])


In [13]:
different_matrix = matrix.new_tensor(matrix.view(1, 6))
different_matrix[0, 1] = 3
print(matrix)
print(different_matrix)

tensor([[1., 2., 1.],
        [1., 1., 1.]])
tensor([[1., 3., 1., 1., 1., 1.]])


/var/folders/8n/4tmx7gjx57j_gn5wps411qp40000gn/T/ipykernel_71736/2171686589.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  different_matrix = matrix.new_tensor(matrix.view(1, 6))
